# Dockerfile.api
FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./functional_scripts /app/functional_scripts

CMD ["uvicorn", "functional_scripts/export_to_csv_fixed:app", "--host", "0.0.0.0", "--port", "8000"]
