FROM python:3.11-slim

# Системные зависимости для psycopg2 и lxml
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем зависимости и устанавливаем
COPY ./requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Копируем функционал
COPY ./functional_scripts /app/functional_scripts

# Запуск парсера
CMD ["python", "functional_scripts/runner.py"]
