version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: motorland-postgres
    environment:
      POSTGRES_USER: parser_user
      POSTGRES_PASSWORD: parser_pass
      POSTGRES_DB: motorland
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres 
volumes:
  postgres_data: